const GET_COURSES = {
  RESET: "GET_COURSES_RESET",
  REQUEST: "GET_COURSES_REQUEST",
  PENDING: "GET_COURSES_PENDING",
  SUCCESS: "GET_COURSES_SUCCESS",
  FAILURE: "GET_COURSES_FAILURE"
};

const ADD_COURSE = {
  RESET: "ADD_COURSE_RESET",
  REQUEST: "ADD_COURSE_REQUEST",
  PENDING: "ADD_COURSE_PENDING",
  SUCCESS: "ADD_COURSE_SUCCESS",
  FAILURE: "ADD_COURSE_FAILURE"
};

const EDIT_COURSE = {
  RESET: "EDIT_COURSE_RESET",
  REQUEST: "EDIT_COURSE_RESET",
  PENDING: "EDIT_COURSE_PENDING",
  SUCCESS: "EDIT_COURSE_SUCCESS",
  FAILURE: "EDIT_COURSE_FAILURE"
};

const DELETE_COURSE = {
  RESET: "DELETE_COURSE_RESET",
  REQUEST: "DELETE_COURSE_REQUEST",
  PENDING: "DELETE_COURSE_PENDING",
  SUCCESS: "DELETE_COURSE_SUCCESS",
  FAILURE: "DELETE_COURSE_FAILURE"
};

export { GET_COURSES, ADD_COURSE, DELETE_COURSE, EDIT_COURSE };
