const GET_AUTHORS_REQUEST = "GET_AUTHORS_REQUEST";
const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS";
const GET_AUTHORS_FAILURE = "GET_AUTHORS_FAILURE";

export { GET_AUTHORS_REQUEST, GET_AUTHORS_SUCCESS, GET_AUTHORS_FAILURE };
