const GET_AUTHORS = {
  PENDING: "GET_AUTHORS_PENDING",
  REQUEST: "GET_AUTHORS_REQUEST",
  SUCCESS: "GET_AUTHORS_SUCCESS",
  FAILURE: "GET_AUTHORS_FAILURE",
  RESET: "GET_AUTHORS_RESET"
};

export { GET_AUTHORS };
