const ADD_COURSE = 'ADD_COURSE'
const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST'
const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS'
const GET_COURSES_FAILURE = 'GET_COURSES_FAILURE'

export {ADD_COURSE, GET_COURSES_REQUEST, GET_COURSES_FAILURE, GET_COURSES_SUCCESS}