const ADD_COURSE = "ADD_COURSE";

const GET_COURSES_REQUEST = "GET_COURSES_REQUEST";
const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
const GET_COURSES_FAILURE = "GET_COURSES_FAILURE";

const GET_AUTHORS_REQUEST = "GET_AUTHORS_REQUEST"
const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS"
const GET_AUTHORS_FAILURE = "GET_AUTHORS_FAILURE"

export {
  ADD_COURSE,
  GET_COURSES_REQUEST,
  GET_COURSES_FAILURE,
  GET_COURSES_SUCCESS,
  GET_AUTHORS_REQUEST,
  GET_AUTHORS_FAILURE,
  GET_AUTHORS_SUCCESS
};
