const GET_COURSES_RESET = "GET_COURSES_RESET";
const GET_COURSES_REQUEST = "GET_COURSES_REQUEST";
const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
const GET_COURSES_FAILURE = "GET_COURSES_FAILURE";

const ADD_COURSE_RESET = "ADD_COURSE_RESET";
const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST";
const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";

const EDIT_COURSE_RESET = "EDIT_COURSE_RESET";
const EDIT_COURSE_REQUEST = "EDIT_COURSE_REQUEST";
const EDIT_COURSE_SUCCESS = "EDIT_COURSE_SUCCESS";
const EDIT_COURSE_FAILURE = "EDIT_COURSE_FAILURE";

const DELETE_COURSE_RESET = "DELETE_COURSE_RESET";
const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
const DELETE_COURSE_FAILURE = "DELETE_COURSE_FAILURE";

export {
  GET_COURSES_RESET,
  GET_COURSES_REQUEST,
  GET_COURSES_SUCCESS,
  GET_COURSES_FAILURE,
  ADD_COURSE_RESET,
  ADD_COURSE_REQUEST,
  ADD_COURSE_SUCCESS,
  ADD_COURSE_FAILURE,
  EDIT_COURSE_RESET,
  EDIT_COURSE_REQUEST,
  EDIT_COURSE_SUCCESS,
  EDIT_COURSE_FAILURE,
  DELETE_COURSE_RESET,
  DELETE_COURSE_REQUEST,
  DELETE_COURSE_SUCCESS,
  DELETE_COURSE_FAILURE
};
