const GET_COURSES_REQUEST = "GET_COURSES_REQUEST";
const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
const GET_COURSES_FAILURE = "GET_COURSES_FAILURE";

const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST";
const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";

export {
    GET_COURSES_REQUEST,
    GET_COURSES_SUCCESS,
    GET_COURSES_FAILURE,
    ADD_COURSE_REQUEST,
    ADD_COURSE_SUCCESS,
    ADD_COURSE_FAILURE
}